version: "3.8"
services:
  backend:
    image: "kingwanyama/springboot-react-fullstack:29.5.2023.14.59.45"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev