version: "3.8"
services:
  backend:
    image: "kingwanyama/springboot-react-fullstack:23.5.2023.16.12.54"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev