version: "3.8"
services:
  backend:
    image: "kingwanyama/springboot-react-fullstack:24.5.2023.11.29.58"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev